overrides:
  node-fetch: "^2.7.0"

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true
